name: Release on Tag

on:
  push:
    tags:
      - '*'        # Любой тег: v1.0.0, v2.1, release-42 и т.д.

permissions:
  contents: write
  
jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Собираем wheel и sdist
      - name: Build package
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: |
            Автоматический релиз для тега ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload sdist (.tar.gz)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/yt_dl_cli-${{ github.ref_name }}.tar.gz
          asset_name: yt_dl_cli-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload wheel (.whl)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/yt_dl_cli-${{ github.ref_name }}-py3-none-any.whl
          asset_name: yt_dl_cli-${{ github.ref_name }}-py3-none-any.whl
          asset_content_type: application/zip

      - name: Create source zip
        run: |
          cd src
          zip -r yt_dl_cli.zip yt_dl_cli

      - name: Upload source zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: src/yt_dl_cli.zip
          asset_name: yt_dl_cli.zip
          asset_content_type: application/zip