name: Release on Tag

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  id-token: write

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build package
        run: |
          python -m pip install --upgrade build
          python -m build

      - name: Extract version
        id: get_version
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
        
      - name: Create source zip
              run: |
                cd src
                zip -r yt_dl_cli.zip yt_dl_cli
                mv yt_dl_cli.zip ../

      - name: Create GitHub Release & Upload Artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            Автоматический релиз для тега ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            dist/yt_dl_cli-${{ steps.get_version.outputs.version }}.tar.gz
            dist/yt_dl_cli-${{ steps.get_version.outputs.version }}-py3-none-any.whl
            src/yt_dl_cli.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}